version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5000"
    env:
    MONGO_URL:
      - "mongodb+srv://mdsarfraaznasir_db_user:c1fICMVB8HUmLMSH@cluster0.6zjy2ss.mongodb.net/?appName=Cluster0"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        REACT_API_URL: 172.31.42.210/3001/api
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    restart: always
